name: 'concord_transforms'
version: '1.0.0'
config-version: 2

# Profile configuration
profile: 'concord'

# Model paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Target directory
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  concord_transforms:
    # Staging models - raw data cleanup
    staging:
      +materialized: view
      +schema: staging

    # Intermediate models - business logic
    intermediate:
      +materialized: view
      +schema: intermediate

    # Mart models - final dimensional models
    marts:
      +materialized: table
      +schema: marts

      # Core business entities
      core:
        +materialized: table

      # Analytics specific
      analytics:
        +materialized: table

      # ML features
      ml_features:
        +materialized: table

# Documentation
docs-paths: ["docs"]

# Seeds configuration
seeds:
  concord_transforms:
    +schema: seeds

# Snapshots configuration
snapshots:
  concord_transforms:
    +target_schema: snapshots
    +unique_key: id
    +strategy: timestamp
    +updated_at: updated_at
