# dbt profile configuration for Delta Lake via DuckDB
concord:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '/opt/dagster/app/data/dbt/concord_bi.duckdb'
      schema: analytics
      threads: 4
      extensions:
        - delta
      settings:
        # Enable Delta Lake extension
        allow_unsigned_extensions: true

    prod:
      type: duckdb
      path: '/opt/dagster/app/data/dbt/concord_bi_prod.duckdb'
      schema: production
      threads: 8
      extensions:
        - delta
      settings:
        allow_unsigned_extensions: true
